### ISSUE TITLE
Use the `eu.org` subdomain

### ISSUE THREAD

**Issue by RaptaG** [Fabulously-Optimized/fabulously-optimized.github.io#6]
The `eu.org` subdomain is offered for free on https://nic.eu.org and it looks better than `github.io` in my opinion

**Comment by osfanbuff63** [comment]
On the other hand, trying to get a DNS server for this and then configuring it to point to github.io for the pages content might not be that easy.

Definitely worth consideration though.

**Comment by Madis0** [comment]
Nice to know. Will consider whenever FO has an actual site 😀

**Comment by RaptaG** [comment]
Cool

**Comment by Madis0** [comment]
See also: https://www.getfreedomain.name/
